package com.room_rental.com.stha.models;

public enum LocalAreal {
    GYM,SWIMMING_POOL,PLAYING_COURT,HOSPITAL,SCHOOL,MONTESSORI,COLLEGE,TEMPLE,RESTAURANTS,SUPER_MARKET,BUS_STOP,POLICE_STATION,BANK,TAXI_STAND,GAS_STATION
}
